### ISSUE TITLE
메세지 오류

### ISSUE THREAD

**Issue by silverprize** [Pyohwan/JakduK#10]
![2015-12-17 1 33 07](https://cloud.githubusercontent.com/assets/860087/11846920/33093414-a45e-11e5-9d61-dec048c2830f.png)

```I wrote this post. can&#39;t choose like or dislike.```

**Comment by Pyohwan** [comment]
https://github.com/Pyohwan/JakduK/commit/9c795c94d98cfc3f29667d69b91b099843529413

아름답게 수정 함.

**Comment by silverprize** [comment]
커밋 코멘트에 "Fixes #10" 이런식으로 "Fixes #이슈번호" 하면 알아서 close로 바껴요
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by Pyohwan** [comment]
안그래도 이거 어떻게 하는지 참 궁금했는데 ㅋㅋ 고마워요.

**Comment by silverprize** [comment]
:+1:
