### ISSUE TITLE
비밀번호 재설정 이후 로그인 하고 나서 redirect 문제

### ISSUE THREAD

**Issue by Pyohwan** [Pyohwan/JakduK#33]
재현 하기.
1. 비밀번호 재설정 
2. 로그인 페이지로 이동한다.
3. 로그인 하면 다시 비밀번호 재설정 페이지로 이동.

기대 결과
이때에는 홈으로 이동하는게 좋을듯.

**Comment by silverprize** [comment]
/confirm_password -> /login 으로 이동했는데 /login에서는 referrer 기억해두지 않으니까 그런거죠?
헤더referrer를 저장하는 방식이 안좋은 것 같아요.
redirect=path 이런식으로 query string으로 하는 게 좋을 것 같아요. 직관적이기도 하고요.

**Comment by Pyohwan** [comment]
이건 제가 볼께요. 스프링 시큐리티 부분이라..
