### ISSUE TITLE
게시판 글쓰기에서 페이지 전환이 일어날경우 경고창 떠야함

### ISSUE THREAD

**Issue by Pyohwan** [Pyohwan/JakduK#48]
게시판 글쓰기에서 페이지 전환이 일어날경우 경고창 떠야함.
예를 들면 무름 버튼을 누르거나 브라우저 뒤로가기를 누르거나 다른 링크를 눌러 이 페이지를 빠져나갈려고 할때 경고창이 떠야함.
어느순간부터 동작을 안하고 있네요.

**Comment by Pyohwan** [comment]
지금 다시 보니 글을 하나라도 안쓰면 아예 안뜨는군요?

**Comment by silverprize** [comment]
초기상태인데 묻는 것이 이상해서 변경이 발생했을때만 묻도록 했습니다.
