### ISSUE TITLE
회원가입 페이지에서 브라우저 멈춤현상

### ISSUE THREAD

**Issue by silverprize** [Pyohwan/JakduK#5]
회원가입 페이지 : https://jakduk.com/user/write
이메일입력란에서 알파벳 20자이상으로 길게 입력하면 브라우저가 멈춤(freezing)

크롬 : 버전 47.0.2526.80 (64-bit)
os : osx 엘캐피탄

**Comment by Pyohwan** [comment]
수정 반영 되었습니다.

**Comment by silverprize** [comment]
commit링크를 레퍼런스 해주는 센스를 발휘해 주십시요!!

**Comment by Pyohwan** [comment]
https://github.com/Pyohwan/JakduK/commit/8d0b23760f10efc661ccbc7b50a608adfeb90b21

github을 잘 다루시는군요. ㅋㅋ
