### ISSUE TITLE
로그인 버튼이 작아서 누르기 까다롭습니다

### ISSUE THREAD

**Issue by silverprize** [Pyohwan/JakduK#7]
![2015-12-15 11 56 46](https://cloud.githubusercontent.com/assets/860087/11813963/9f91ab98-a387-11e5-89b6-65f6b5f7c3f8.png)
심지어 딱 "로그인"글자만 마우스 포인터 인식 영역입니다. 검은띠까지만 넓혀도 조금 나을 것 같습니다만
어떻게 생각하시나요?

**Comment by Pyohwan** [comment]
글자 폰트를 12px -> 15px로 증가.
jakduk-web/WebContent/resources/jakduk/css/jakduk.css

https://github.com/Pyohwan/JakduK/commit/ff38cd43bfb64868a3ee7ed230f92300f84e3c85

**Comment by silverprize** [comment]
배포좀...

**Comment by Pyohwan** [comment]
금일 중으로 배포하겠습니다.

**Comment by Pyohwan** [comment]
배포 완료.
