### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by Pyohwan** [Pyohwan/JakduK#8]
![jakduk_eclipse01](https://cloud.githubusercontent.com/assets/1825642/11830215/1c4eb6ae-a3e6-11e5-9397-62b8e21a4a63.jpeg)

**Comment by Pyohwan** [comment]
![_jakduk](https://cloud.githubusercontent.com/assets/1825642/11832753/36ccd07e-a3ff-11e5-857b-78d26f97d07f.png)

**Comment by Pyohwan** [comment]
![2015-12-18 22 29 31](https://cloud.githubusercontent.com/assets/1825642/11897908/e05a3900-a5d6-11e5-9aea-e5738576b037.png)

**Comment by Pyohwan** [comment]
![2015-12-18 22 42 24](https://cloud.githubusercontent.com/assets/1825642/11898352/9cc3810c-a5da-11e5-9da7-d5b6ea610484.png)

**Comment by silverprize** [comment]
어디에 쓰는 이미지를 업로드해요? 아바타?

**Comment by Pyohwan** [comment]
IntelliJ IDEA 15.0.2 에서 JakduK 프로젝트 구성하기 하고 있습니다.

**Comment by silverprize** [comment]
질렀구나~
:+1: :+1: :+1:

**Comment by Pyohwan** [comment]
![2015-12-19 00 38 38](https://cloud.githubusercontent.com/assets/1825642/11900941/16604d2c-a5ec-11e5-88c7-5f9311d03237.png)

**Comment by Pyohwan** [comment]
아직 지르진 않았고 30일 버전으로 사용중입니다. For Open Source projects 신청하면 공짜라길래 신청은 해두었는데 잘 될지는 모르겠네요.

**Comment by silverprize** [comment]
:-1: :-1: :-1:

**Comment by Pyohwan** [comment]
![jakduk_project01](https://cloud.githubusercontent.com/assets/1825642/11901007/8dc10028-a5ec-11e5-94d0-907b619294bf.png)

**Comment by Pyohwan** [comment]
![2015-12-19 00 47 53](https://cloud.githubusercontent.com/assets/1825642/11901068/e35581b2-a5ec-11e5-8f84-fd7d187e6da7.png)

**Comment by Pyohwan** [comment]
![jakduk_edit_configurations01](https://cloud.githubusercontent.com/assets/1825642/11901103/19ec5f34-a5ed-11e5-9660-b2268a6b9f2f.png)

**Comment by Pyohwan** [comment]
![2015-12-19 00 50 23](https://cloud.githubusercontent.com/assets/1825642/11901141/4a494322-a5ed-11e5-9c28-9fabfd8f27db.png)

**Comment by Pyohwan** [comment]
![2015-12-19 00 49 48](https://cloud.githubusercontent.com/assets/1825642/11901179/7c02e3c8-a5ed-11e5-94e6-09ea6f16bba1.png)

**Comment by Pyohwan** [comment]
![2015-12-19 00 50 15](https://cloud.githubusercontent.com/assets/1825642/11901199/955e8f98-a5ed-11e5-94ad-ce34de37f959.png)

**Comment by silverprize** [comment]
헐퀴 이슈를 이미지 저장소로 쓰는 거였군요

**Comment by Pyohwan** [comment]
그림 올리는 방법이 딱히 없더라고요 ㅋㅋ

**Comment by Pyohwan** [comment]
![2016-01-03 22 42 48](https://cloud.githubusercontent.com/assets/1825642/12078987/68f54462-b26b-11e5-8e21-88f44e6e009b.png)

**Comment by Pyohwan** [comment]
![2016-01-03 22 44 02](https://cloud.githubusercontent.com/assets/1825642/12078991/831c126c-b26b-11e5-9d31-aef143168d6d.png)

**Comment by silverprize** [comment]
이런 편법말고 전용 레포지토리 만들면 이미지 링크 편하게 할 수 있데요
https://help.github.com/articles/adding-images-to-wikis/
http://mikehadlow.blogspot.kr/2014/03/how-to-add-images-to-github-wiki.html

**Comment by silverprize** [comment]
[patch.zip](https://github.com/Pyohwan/JakduK/files/104716/patch.zip)
위키 레포지토리는 오너만 푸쉬 할 수 있어서 패치파일로 올립니다.
https://github.com/Pyohwan/JakduK.wiki.git 클론하셔서 위 패치를 적용하시고 이 이슈를 닫아주시면 좋을 것 같습니다.
추후에 필요한 이미지들은 위키 레포지토리에 푸쉬하시면 됩니다.

**Comment by Pyohwan** [comment]
적용 완료.

**Comment by silverprize** [comment]
![jetbrains](https://user-images.githubusercontent.com/860087/40435278-47c3c99c-5eeb-11e8-9977-cfa64f2c8cda.png)
걍 이렇게 하는게 젤 편하네요.
