### ISSUE TITLE
로그인안한 상태에서 댓글 남기기 textarea클릭하면 나오는 alert

### ISSUE THREAD

**Issue by silverprize** [Pyohwan/JakduK#9]
"취소"버튼을 누르면 "먼저 로그인부터 해야 글을 쓸 수 있어요." 물어보고
"취소"버튼을 누르면 "먼저 로그인부터 해야 글을 쓸 수 있어요." 물어보고
"취소"버튼을 누르면 "먼저 로그인부터 해야 글을 쓸 수 있어요." 물어보고
"취소"버튼을 누르면 "먼저 로그인부터 해야 글을 쓸 수 있어요." 물어보고
반복

"확인"버튼을 누르면 "먼저 로그인부터 해야 글을 쓸 수 있어요." 물어보고
"확인"버튼을 누르면 로그인 페이지로 이동

**Comment by silverprize** [comment]
댓글에 "♪" 이문자는 왜 기본으로 들어가 있는 건가요?
![2015-12-17 1 28 24](https://cloud.githubusercontent.com/assets/860087/11846793/7df8c8aa-a45d-11e5-9878-d0a8e67ca625.png)

**Comment by Pyohwan** [comment]
일단 위에꺼는 focus 이벤트 발생시 로그인 여부를 체크를 하는데, 크롬에서만 발생하고 있습니다. focus 말고 다른 이벤트로의 변경을 고려해 보아야 겠네요.

아래 ♪ 가 들어가 있는 이유는, 공백으로 줄 경우 에디터(summernote)의 height가 아주 작아져서 클릭하는 포인터도 매우 좁고, 글쓰기도 불편하고 해서 기본값으로 넣어준 것입니다.

**Comment by Pyohwan** [comment]
https://github.com/Pyohwan/JakduK/commit/bbfe092b5857fd4ca6c6f690e98f42ad7b0e94e9

* summernote 경고창의 경우 onChange -> onKeyUp 이벤트로 변경
* summernote의 placeholder를 둘려고 했으나, 아직까지 summernote placeholder 문제가 많은듯.. 다시 ♪로 돌아감.

**Comment by Pyohwan** [comment]
배포 완료.
